### ISSUE TITLE
Typo was not fixed in NPM

### ISSUE THREAD

**Issue by AlmogCohen** [justusbluemer/puppeteer-datalayer#3]
Hi there! Thanks for your work 👍 

I've just did `npm install` to the package, got version 1.0.1, and still have this typo in the code https://github.com/justusbluemer/puppeteer-datalayer/commit/b885c55cc541a5ab3fad14160515128be1cd6411

I had to debug my way there to understand why things are not working :) Would you mind pushing a new version to NPM?

![Screen Shot 2020-10-01 at 9 51 01 AM](https://user-images.githubusercontent.com/3888998/94777138-9e0f9d80-03cb-11eb-875c-148b9627246f.png)

**Comment by AlmogCohen** [comment]
For now, I just install the master branch code of this repo using npm

**Comment by justusbluemer** [comment]
This should be fixed now
